- eoscompanion/dummy_feed.py
- eoscompanion/routes.py
https://phabricator.endlessm.com/T21765
> Feed: dummy reponse for testing purposes

- eoscompanion/dummy_feed.py
https://phabricator.endlessm.com/T21765
> Feed: remove unused lists for details

- eoscompanion/dummy_feed.py
> DummyFeed, artwork: add author and date information

- data/templates/mobile-article-wrapper.mst
- eoscompanion/content_adjusters.py
https://phabricator.endlessm.com/T22047
> eoscompanion: Also render page title with HTML content

- eoscompanion/dummy_feed.py
s/contentType/itemType and add another field for the contentType
> Feed: update dummy feed to latest spec

- Makefile.am.service.inc
- com.endlessm.CompanionAppService.json.in
- eoscompanion/applications_query.py
- eoscompanion/ekn_content_adjuster.py
- eoscompanion/eknservices_bridge.py
- eoscompanion/routes.py
- src/eos-companion-app-integration-helper.c
- src/eos-companion-app-integration-helper.h
- src/eos-companion-app-service-app-info.c
- src/eos-companion-app-service-app-info.h
- test/test_service.py
https://phabricator.endlessm.com/T22168
> T22168: Support EknServices2 and EknServices3

- eoscompanion/routes.py
- test/test_service.py
https://phabricator.endlessm.com/T22427
> routes: Handle "FAILED" error when doing content search

- com.endlessm.CompanionAppService.json.in
- data/eos-companion-app-helper.conf
- src/eos-companion-app-integration-helper.c
https://phabricator.endlessm.com/T22393
> T22393: Support SDK1 apps

- com.endlessm.CompanionAppService.json.in
- eoscompanion/eknservices_bridge.py
- eoscompanion/format.py
- eoscompanion/main.py
- eoscompanion/routes.py
- test/test_service.py
https://phabricator.endlessm.com/T22203
> T22203: Add support for /feed endpoint from libcontentfeed

- src/eos-companion-app-integration-helper.c
gtk_icon_theme_load_icon_data is not thread safe as it
mutates an internal cache both when the pixbuf is unreffed and
when an icon is loaded. Instead of putting all that behind
a thread, look up the icon info in the cache first on the main
thread and then load the icon data asynchronously.
https://phabricator.endlessm.com/T22584
> helper: Use gtk_icon_info_load_icon_async, as opposed to threads

- eoscompanion/ekn_content_adjuster.py
https://phabricator.endlessm.com/T22356
> Include collapse-infotable script

- eoscompanion/eknservices_bridge.py
- eoscompanion/main.py
- eoscompanion/routes.py
- test/test_service.py
https://phabricator.endlessm.com/T22542
> eoscompanion: Rename from EosDiscoveryFeed -> ContentFeed

- eoscompanion/applications_query.py
- eoscompanion/content_streaming.py
- eoscompanion/ekn_content_adjuster.py
- eoscompanion/ekn_query.py
- eoscompanion/eknservices_bridge.py
- eoscompanion/license_content_adjuster.py
- eoscompanion/routes.py
- test/test_service.py
We'll use this later to cancel in flight requests in case of an interrupt.  https://phabricator.endlessm.com/T21897
> routes: Add cancellability middleware and cancellable param

- eoscompanion/format.py
- eoscompanion/v2_routes.py
- src/eos-companion-app-integration-helper.h
- test/routes_v2.py
https://phabricator.endlessm.com/T22780
> T22780: Add referrer to generated content data uris

- test/test_service.py
https://phabricator.endlessm.com/T22776
> test: Add some more detail on the GIO caching issue.

- eoscompanion/ekn_query.py
However, don't filter out sets if none of them were marked
featured.
https://phabricator.endlessm.com/T22957
> ekn_query: Explicitly filter out sets not marked featured

- Makefile.am.service.inc
- eoscompanion/applications_query.py
- eoscompanion/content_streaming.py
- eoscompanion/ekn_content_adjuster.py
- eoscompanion/ekn_query.py
- eoscompanion/license_content_adjuster.py
- eoscompanion/middlewares.py
- eoscompanion/server.py
- eoscompanion/service.py
- eoscompanion/v1_routes.py
- eoscompanion/v2_routes.py
- src/eos-companion-app-integration-helper.c
- src/eos-companion-app-integration-helper.h
- src/eos-companion-app-service-managed-cache-private.h
- src/eos-companion-app-service-managed-cache.c
- src/eos-companion-app-service-managed-cache.h
- test/routes_v1.py
- test/routes_v2.py
- test/service_test_helpers.py
https://phabricator.endlessm.com/T20300
> T20300: Move all the caches to the toplevel and drop them if the Flatpak state changes

- src/eos-companion-app-integration-helper.c
https://phabricator.endlessm.com/T23277
> integration: add support for SDK5 apps

- com.endlessm.CompanionAppService.json.in
- configure.ac
- src/eos-companion-app-integration-helper.c
https://phabricator.endlessm.com/T23269
> T23269 stable

- src/eos-companion-app-integration-helper.c
Doing so is pointless anyway since all content apps are
flatpaks and just exposes us to potential deadloks inside
of g_desktop_app_info_new when calling it from N threads.
https://phabricator.endlessm.com/T23650
> helper: Don't call g_desktop_app_info_new as a fallback
